name: Docker Compose Deployment

on:
  push:
    branches:
      - main  # Change this to match your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change the runner to your preferred environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository code

      - name: Set up Docker Compose
        uses: docker/compose-cli@v1  # This action sets up Docker Compose CLI

      - name: Build and run Docker Compose services
        run: |
          docker compose up -d  # Modify this command as needed to build and run your services defined in the Docker Compose file
